version: 0.0
os: linux
files:
  - source: hello-ops-0.1-SNAPSHOT.jar.tar
    destination: /opt/aws-demo/
hooks:
  AfterInstall:
    - location: tar xvf hello-ops-0.1-SNAPSHOT.jar.tar
      timeout: 1000
  ApplicationStart:
    - location: java -jar /opt/aws-demo/hello-ops-0.1-SNAPSHOT.jar
      timeout: 3600
