version: 0.0
os: linux
files:
  - source: hello-ops-0.1-SNAPSHOT.jar
    destination: /opt/aws-demo/
hooks:
  ApplicationStart:
    - location: java -jar /opt/aws-demo/hello-ops-0.1-SNAPSHOT.jar
      timeout: 3600
