version: 0.1

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn clean -U package
  post_build:
    commands:
      - echo Build completed on `date`
      - pwd
      - cp appspec.yml target/appsepc.yml
      - cd target && (tar -cf hello-ops-0.1-SNAPSHOT.jar.tar hello-ops-0.1-SNAPSHOT.jar appspec.yml)
artifacts:
  files:
    - target/hello-ops-0.1-SNAPSHOT.jar.tar
