version: 0.0
os: linux
files:
  - source: hello-ops-0.1-SNAPSHOT.jar
    destination: /opt/aws-demo/
hooks:
  BeforeInstall:
    - location: touch a.sh
  ApplicationStart:
    - location: java -jar hello-ops-0.1-SNAPSHOT.jar
      timeout: 3600
